train:
  seed: 8
  data:
    data_path: data/raw/data.csv
    period: 1y
    info_keys:
      - symbol
  need_plot: True
  tda:
    sliding:
      window_size: 5
      stride: 2
    embedder:
      dimension: 5
      delay: 2
predict:
  seed: 8
  data:
    period: 2mo
    info_keys:
      - symbol
      - shortName
      - sector
      - industry
      - country
