train:
  seed: 8
  data:
    data_path: data/raw/data.csv
    sliding_path: data/models/sliding
    embedder_path: data/models/embedder
    persistence_path: data/models/vr_persistence
    entropy_path: data/models/p_entropy
    prediction_path: data/prediction.csv
    period: 1y
    info_keys:
      - symbol
  need_plot: True
  tda:
    sliding:
      window_size: 5
      stride: 2
    embedder:
      dimension: 5
      delay: 2
  mlflow:
    tracking_uri: http://localhost:5000
predict:
  seed: 8
  data:
    period: 3mo
    info_keys:
      - symbol
      - shortName
      - sector
      - industry
      - country
  mlflow:
    tracking_uri: http://localhost:5000